### ISSUE TITLE
Create a tag

### ISSUE THREAD

**Issue by GoToLoop** [therewasaguy/p5.midi#2]
Can you create a tag for this project so it's downloadable via this CDN, please?
http://CDN.JSDelivr.net/gh/therewasaguy/p5.midi/p5.midi.js

**Comment by therewasaguy** [comment]
sure @GoToLoop, just added a tag and looks like it did the trick!

https://cdn.jsdelivr.net/gh/therewasaguy/p5.midi@v0.01/p5.midi.js

It's been a couple years since I looked at this library, I hope it's useful and welcome any improvements

**Comment by GoToLoop** [comment]
Gr8, thx! It's for this forum thread:  ^_^
https://forum.Processing.org/two/discussion/22815/minim-alternatives-for-minim-in-p5-js

Strange it needs `@v0.01` in order to work:   :-(
http://CDN.JSDelivr.net/gh/therewasaguy/p5.midi@v0.01/p5.midi.js

Maybe URL version w/o `@v0.01` will be enabled later...

BtW, there's also auto-minification:   ;-D
http://CDN.JSDelivr.net/gh/therewasaguy/p5.midi@v0.01/p5.midi.min.js

**Comment by MartinKolarik** [comment]
@GoToLoop urls without version only work with valid semver tags.

**Comment by GoToLoop** [comment]
So instead of `v0.01`, it shoulda been `0.0.1` or even `1.0.0`?

**Comment by MartinKolarik** [comment]
yes

**Comment by therewasaguy** [comment]
ah, updated! Thanks @GoToLoop @MartinKolarik
